---
name: "run-uptime-monitor"

# This runs too often and is clogging up the commit history on my profile.
# Disabling this right now.
# on:
#   schedule:
#     - cron: '*/5 * * * *'
#   workflow_dispatch:

jobs:
  run-monitor:
    name: "Run uptime monitor"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run uptime monitor
        run: python main.py

      - name: Commit status.json
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_message: 'Update status.json'
          file_pattern: 'status.json'
          branch: main
